FROM node:16-alpine3.14 as base
WORKDIR /app

RUN apk add curl bash --no-cache
RUN curl -sf https://gobinaries.com/tj/node-prune | sh

#----------------BUILD-----------------
FROM base as builder
COPY ./src ./src
COPY package*.json ./

RUN npm install
RUN npm prune --production && node-prune

#----------------RELEASE-----------------
FROM node:16-alpine3.14 as release
COPY --from=builder /app/ ./

ARG APP_NAME
ENV APP_NAME=${APP_NAME}

ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}

EXPOSE 3000

CMD ["node", "./src/main.js"]

# docker build -t dockerlabs-api:1.0 .
# docker build -t dockerlabs-api:1.0 --build-arg APP_NAME=nuevaapi --build-arg=APP_VERSION=1.0.0  .

# docker run --rm --name dockerlabs-api -p 3000:3000 dockerlabs-api:1.0
# docker run --rm --name dockerlabs-api -p 3000:3000 -e APP_NAME=Dockerlabs-API -e APP_VERSION=2  --network cloudNetwork dockerlabs-api:1.0
