version: '3.7'

services:
  todo:
    container_name: todo-username
    image: cachac/todo-demo:1.0
    restart: unless-stopped

    mem_limit: 50m
    cpus: 0.3

    ports:
      - 8080:3000

    volumes:
      - todo-data:/etc/todos

volumes:
  todo-data: {}
