version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8080:3000
    working_dir: /app
    restart: unless-stopped
    mem_limit: 50m
    cpus: 0.3
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DB: todos
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
