version: '3'

services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - 80:80
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

  # whoami:
  #   image: jwilder/whoami
  #   environment:
  #     - VIRTUAL_HOST=whoami.local
  www:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ../Hello_docker.html:/usr/share/nginx/html/index.html:ro
