version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dockerlabs:
    image: nginx
    restart: always
    expose:
      - 80
    volumes:
      - ../Hello_docker.html:/usr/share/nginx/html/index.html:ro
    environment:
      - VIRTUAL_HOST=dockerlabs.tk,www.dockerlabs.tk
      - LETSENCRYPT_HOST=dockerlabs.tk,www.dockerlabs.tk
      - LETSENCRYPT_EMAIL=info@dockerlabs.com
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5000"
        tag: "multidocker"
    depends_on:
      - nginx-proxy
      - letsencrypt

  dockerlabs-alt:
    image: nginx
    restart: always
    expose:
      - 80
    volumes:
      - ./Hello_docker_alt.html:/usr/share/nginx/html/index.html:ro
    environment:
      - VIRTUAL_HOST=alt.dockerlabs.tk,www.alt.dockerlabs.tk
      - LETSENCRYPT_HOST=alt.dockerlabs.tk,www.alt.dockerlabs.tk
      - LETSENCRYPT_EMAIL=info@dockerlabs.com
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5000"
        tag: "multidocker"
    depends_on:
      - nginx-proxy
      - letsencrypt

volumes:
  certs:
  html:
  vhostd:
