version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # whoami:
  #   image: jwilder/whoami
  #   environment:
  #     - VIRTUAL_HOST=whoami.local
  dockerlabs:
    image: nginx
    container_name: dockerlabs
    restart: always
    expose:
      - 80
    volumes:
      - ../Hello_docker.html:/usr/share/nginx/html/index.html:ro
    environment:
      - VIRTUAL_HOST=dockerlabs.tk,www.dockerlabs.tk
