version: '3.2'
networks:
  net-monitoreo:
    name: net-monitoreo
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 12.0.0.0/27
          gateway: 12.0.0.1

volumes:
  grafana:
  prometheus:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    mem_limit: 200m
    # mem_reservation: 100m
    memswap_limit: 200m
    cpus: 0.5
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus:/prometheus
    networks:
    - net-monitoreo

    depends_on:
    - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    mem_limit: 200m
    # mem_reservation: 100m
    memswap_limit: 200m
    cpus: 0.5
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
    - net-monitoreo
    depends_on:
    - redis

  node-exporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    mem_limit: 200m
    # mem_reservation: 100m
    memswap_limit: 200m
    cpus: 0.5
    ports:
    - 9100:9100
    networks:
    - net-monitoreo

  redis:
    image: redis:latest
    container_name: redis
    mem_limit: 200m
    # mem_reservation: 100m
    memswap_limit: 200m
    cpus: 0.5
    ports:
    - 6379:6379

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    mem_limit: 200m
    # mem_reservation: 100m
    memswap_limit: 200m
    cpus: 0.5
    volumes:
    - grafana:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
    - net-monitoreo
