route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#docker'
            api_url: 'https://hooks.slack.com/services/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'
